# Do not include credentials in this file for production, use environment variables instead
cdoge25-postgres-ecom:
  outputs:
    dev:
      connect_timeout: 10
      dbname: ecom
      host: host.docker.internal
      keepalives_idle: 0
      password: dbtPassword123
      port: 5432
      retries: 1
      role: transform
      schema: dev
      search_path: null
      sslcert: null
      sslkey: null
      sslmode: null
      sslrootcert: null
      threads: 1
      type: postgres
      user: dbt
    prod:
      connect_timeout: 10
      dbname: ecom
      host: host.docker.internal
      keepalives_idle: 0
      password: dbtPassword123
      port: 5432
      retries: 1
      role: transform
      schema: prod      
      search_path: null
      sslcert: null 
      sslkey: null
      sslmode: null
      sslrootcert: null
      threads: 1
      type: postgres
      user: dbt
  target: dev
cdoge25-snowflake-ecom:
  outputs:
    dev:
      account: "{{ env_var('DBT_SF_ACCOUNT') }}"
      database: "{{ env_var('DBT_SF_DATABASE') }}"
      password: "{{ env_var('DBT_SF_PASSWORD') }}"
      role: "{{ env_var('DBT_SF_ROLE') }}"
      schema: DEV
      threads: 10
      type: snowflake
      user: "{{ env_var('DBT_SF_USER') }}"
      warehouse: COMPUTE_WH
  target: dev
