# Do not include credentials in this file for production, use environment variables instead
cdoge25-postgres-ecom:
  outputs:
    marts:
      connect_timeout: 10
      dbname: ecom
      host: localhost
      keepalives_idle: 0
      password: dbtPassword123
      port: 5432
      retries: 1
      role: transform
      schema: marts
      search_path: null
      sslcert: null
      sslkey: null
      sslmode: null
      sslrootcert: null
      threads: 1
      type: postgres
      user: dbt
  target: marts
cdoge25-snowflake-ecom:
  outputs:
    marts:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      schema: marts
      threads: 10
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: COMPUTE_WH
  target: marts
